POST http://localhost:8000/user/
Content-type: application/json

{
    "username": "Demo",
    "password": "123"
}

###

POST http://localhost:8000/user/login
Content-type: application/json

{
    "username": "Demo",
    "password": "123"
}

###

GET http://localhost:8000/user
