POST http://localhost:8000/user/
Content-type: application/json

{
    "name": "First",
    "password": "password"
}

###

POST http://localhost:8000/user/login
Content-type: application/json

{
    "name": "First",
    "password": "paword"
}


###

GET http://localhost:8000/user

